[colors.bright]
black = "#928374"
blue = "#83a598"
cyan = "#8ec07c"
green = "#b8bb26"
magenta = "#d3869b"
red = "#fb4934"
white = "#ebdbb2"
yellow = "#fabd2f"

[colors.normal]
black = "#282828"
blue = "#458588"
cyan = "#689d6a"
green = "#98971a"
magenta = "#b16286"
red = "#cc241d"
white = "#a89984"
yellow = "#d79921"

[colors.primary]
background = "#282828"
foreground = "#ebdbb2"

[env]
TERM = "alacritty"
WINIT_X11_SCALE_FACTOR = "1.0"

[font]
size = 14

[font.bold]
family = "FiraMono Nerd Font"
style = "Bold"

[font.italic]
family = "FiraMono Nerd Font"
style = "Italic"

[font.normal]
family = "FiraMono Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Alt"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Alt"

[window]
dynamic_padding = true
dynamic_title = true

[window.padding]
x = 8
y = 0

# [[keyboard.bindings]]
# key = "Return"
# mods = "Shift"
# chars = "\x1b\r"
